command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "SERVING_ENDPOINT"
    valueFrom: "serving-endpoint"
  - name: "MLFLOW_TRACKING_URI"
    value: "databricks"
  - name: "MLFLOW_EXPERIMENT_ID"
    value: "3040165994661313"
